const API_PLANET_CALL_REQUEST = 'API_PLANET_CALL_REQUEST';
const API_PLANET_CALL_SUCCESS = 'API_PLANET_CALL_SUCCESS';
const API_PLANET_CALL_FAILURE = 'API_PLANET_CALL_FAILURE';

export { API_PLANET_CALL_REQUEST, API_PLANET_CALL_SUCCESS, API_PLANET_CALL_FAILURE };
