const API_LOGIN_CALL_REQUEST = 'API_LOGIN_CALL_REQUEST';
const API_LOGIN_CALL_SUCCESS = 'API_LOGIN_CALL_SUCCESS';
const API_LOGIN_CALL_FAILURE = 'API_LOGIN_CALL_FAILURE';

export { API_LOGIN_CALL_REQUEST, API_LOGIN_CALL_SUCCESS, API_LOGIN_CALL_FAILURE };
